BS_Project-15112018-20190513T013456Z-001 - Copy/BS_Project-15112018/BS_Project/Areas/Store/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BS_Project.Areas.Store.Controllers
{
    public class HomeController : Controller
    {
        // GET: Store/Home
        public ActionResult Index()
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("Login", "AccountAdmin");
            }
            return View();
        }
    }
}

BS_Project-15112018-20190513T013456Z-001 - Copy/BS_Project-15112018/BS_Project/Areas/Store/Controllers/PublisherController.cs
using BS_Project.DAO;
using BS_Project.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BS_Project.Areas.Store.Controllers
{
    public class PublisherController : Controller
    {
        // GET: Store/Publisher
        public ActionResult Index(string searchString, int page = 1, int pageSize = 5)
        {
            var dao = new PublisherDAO();
            var model = dao.ListAllPaging(searchString, page, pageSize);
            ViewBag.SearchString = searchString;
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Publisher publisher)
        {
            if (ModelState.IsValid)
            {
                var dao = new PublisherDAO();
                int result = dao.Insert(publisher);
                if (result > 0)
                {
                    return RedirectToAction("Index", "Publisher");
                }
                else
                {
                    ModelState.AddModelError("", "Thêm Category không thành công");
                }
            }
            return View("Index");
        }

        public ActionResult Edit(int id)
        {
            var publisherDetail = new PublisherDAO().ViewDetail(id);
            return View(publisherDetail);
        }

        [HttpPost]
        public ActionResult Edit(Publisher publisher)
        {
            if (ModelState.IsValid)
            {
                var dao = new PublisherDAO();
                var result = dao.Update(publisher);
                if (result)
                {
                    return RedirectToAction("Index", "Publisher");
                }
                else
                {
                    ModelState.AddModelError("", "Publisher không cập nhật thành công");
                }
            }
            return View("Index");
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            var result = new PublisherDAO().Delete(id);
            return RedirectToAction("Index", "Publisher");
        }
    }
}

BS_Project-15112018-20190513T013456Z-001 - Copy/BS_Project-15112018/BS_Project/Controllers/AuthorController.cs
using BS_Project.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BS_Project.Controllers
{
    public class AuthorController : Controller
    {
        private BSDBContext db = null;
        // GET: Author
        /// <summary>
        /// lay thong tin tac gia
        /// </summary>
        /// <param name="bookID"></param>
        /// <returns></returns>
        public PartialViewResult returnAuthor(int bookID)
        {
            db = new BSDBContext();
            var author = db.Books.Find(bookID).Authors.ToList();
            return PartialView(author);
        }
    }
}

BS_Project-15112018-20190513T013456Z-001 - Copy/BS_Project-15112018/BS_Project/Controllers/BookController.cs
using BS_Project.EF;
using BS_Project.Models;
using System;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;

namespace BS_Project.Controllers
{
    public class BookController : Controller
    {
        BSDBContext db = new BSDBContext();
        RemoveSignVNModel removeSign = new RemoveSignVNModel();
        CommonConstant cm = new CommonConstant();
        private static int pageSize = 6;
        // GET: Book
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult ShowBook()
        {
            return View();
        }

        /// <summary>
        /// hiển thị tất cả các sách
        /// </summary>
        /// <param name="page"></param>
        /// <param name="sortID"></param>
        /// <returns>trả về danh sách tất cả các book</returns>
        [HttpGet]
        public ActionResult ShowAllBook(int page = 0, int sortID = 0)
        {
            //hiện tại dữ liệu còn ít, nên test 1 trang có 3 sản phẩm để làm phân trang
            // tương lai sẽ cho người dùng chọn pageSize
            if (Request.QueryString["page"] != null)
            {
                page = int.Parse(Request.QueryString["page"].ToString());
            }

            //gọi procedure ShowBookFollowCategory
            var allBooks = db.Database.SqlQuery<Book>("ShowAllBook @sortID",
                new SqlParameter("@sortID", sortID)).ToList();

            // số book hiển thị
            var books = allBooks.Skip(page * 3).Take(pageSize).ToList();
            var totalPage = (int)Math.Ceiling((decimal)allBooks.Count / pageSize);

            return PartialView("~/Views/Shared/_ShowAllBook.cshtml", new PaggingModel
            {
                Books = books,
                TotalPage = totalPage
            });
        }

        /// <summary>
        /// Show thể loại của các loại sách
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ShowCategoriesBook()
        {
            var allCategories = db.Categories.ToList();
            var totalCate = allCategories.Count;
            return PartialView("~/Views/Shared/_ShowCategoriesBook.cshtml", new PaggingModel
            {
                ToTalCategories = totalCate,
                Categories = allCategories
            });
        }

        /// <summary>
        /// đếm số lượng sách của từng thể loại
        /// </summary>
        /// <param name="idCate">id thể loại</param>
        /// <returns>số sách theo thể loại</returns>
        public int GetCountForCategory(int idCate)
        {
            return db.Categories.Find(idCate).Books.Count();
        }

        /// <summary>
        /// hàm lấy ảnh đầu tiên của quyển sách để hiển thị 
        /// </summary>
        /// <param name="idImage">idpoolimage của từng sách</param>
        /// <returns>trả về chuỗi string chứa hình</returns>
        public string GetFirstImage(int idImage)
        {
            string image = "";
            image = db.Images.Where(x => x.ImageBoolID == idImage).First().ImageURL;
            return image;
        }

        /// <summary>
        /// định dạng tiền vnđ
        /// </summary>
        /// <param name="money">chuỗi số cần format tiền</param>
        /// <returns></returns>
        public string FormatMoney(string money)
        {
            return cm.formatMoney(money, ".");
        }

        /// <summary>
        /// Hiển thị sách theo nhà phát hành
        /// </summary>
        /// <param name="page">page hiện tại</param>
        /// <param name="idPublisher">id của loại sách</param>
        /// <param name="sortID">sortid = 1 theo sách xem nhiều, = 2 sắp xếp theo ngày phát hành, = 3 sách được đặt nhiều</param>
        /// <returns>trả về 1 partialview, kèm theo 1 model books truyền qua</returns>
        [HttpGet]
        public ActionResult ShowBookFollowPublisher(int page = 0, int idPublisher = 0, int sortID = 0)
        {
            //hiện tại dữ liệu còn ít, nên test 1 trang có 3 sản phẩm để làm phân trang
            //tương lai sẽ cho người dùng chọn pageSize
            if (Request.QueryString["idPublisher"] != null)
            {
                idPublisher = int.Parse(Request.QueryString["idPublisher"].ToString());
            }
            if (Request.QueryString["page"] != null)
            {
                page = int.Parse(Request.QueryString["page"].ToString());
            }

            //gọi procedure ShowBookFollowCategory
            var allBooks = db.Database.SqlQuery<Book>("ShowBookFollowPublisher @publicsherID, @sortID",
                new SqlParameter("@publicsherID", idPublisher), new SqlParameter("@sortID", sortID)).ToList();

            // số book hiển thị
            var books = allBooks.Skip(page * 3).Take(pageSize).ToList();
            var totalPage = (int)Math.Ceiling((decimal)allBooks.Count / pageSize);
            return PartialView("~/Views/Shared/_ShowBookFollowPublisher.cshtml", new PaggingModel
            {
                Books = books,
                TotalPage = totalPage,
                idPublisher = idPublisher
            });
        }

        /// <summary>
        /// Hiển thị sách theo thể loại sách
        /// </summary>
        /// <param name="page">page hiện tại</param>
        /// <param name="idCategory">id của loại sách</param>
        /// <param name="sortID">sortid = 1 theo sách xem nhiều, = 2 sắp xếp theo ngày phát hành, = 3 sách được đặt nhiều</param>
        /// <returns>trả về 1 partialview, kèm theo 1 model books truyền qua</returns>
        [HttpGet]
        public ActionResult ShowBookFollowCategory(int page = 0, int idCategory = 0, int sortID = 0)
        {
            // hiện tại dữ liệu còn ít, nên test 1 trang có 3 sản phẩm để làm phân trang
            // tương lai sẽ cho người dùng chọn pageSize
            if (Request.QueryString["idcategory"] != null)
            {
                idCategory = int.Parse(Request.QueryString["idcategory"].ToString());
            }
            if (Request.QueryString["page"] != null)
            {
                page = int.Parse(Request.QueryString["page"].ToString());
            }
            //gọi procedure ShowBookFollowCategory
            var allBooks = db.Database.SqlQuery<Book>("ShowBookFollowCategory @categoryID, @sortID",
                new SqlParameter("@categoryID", idCategory), new SqlParameter("@sortID", sortID)).ToList();
            // số book hiển thị
            var books = allBooks.Skip(page * 3).Take(pageSize).ToList();
            var totalPage = (int)Math.Ceiling((decimal)allBooks.Count / pageSize);
            return PartialView("~/Views/Shared/_ShowBookFollowCategory.cshtml", new PaggingModel
            {
                Books = books,
                TotalPage = totalPage,
                IdCategory = idCategory
            });
        }
        /// <summary>
        /// hiển thị dữ liệu
        /// </summary>
        /// <param name="page"></param>
        /// <param name="sortID"></param>
        /// <param name="keySearch"></param>
        [HttpGet]
        public ActionResult ShowBookFollowKeySearch(int page = 0, string keySearch = "")
        {
            //hiện tại dữ liệu còn ít, nên test 1 trang có 1 sản phẩm để làm phân trang
            // tương lai sẽ cho người dùng chọn pageSize
            keySearch = Request.QueryString["keysearch"].ToString();
            if (Request.QueryString["page"] != null)
            {
                page = int.Parse(Request.QueryString["page"].ToString());
            }
            // remove dấu tiếng việt
            string removeUnicodeKeySearch = removeSign.RemoveSign4VietnameseString(keySearch);

            var allBooks = db.Database.SqlQuery<Book>("ShowBookFollowKeySearch @keySearch",
                new SqlParameter("@keySearch", removeUnicodeKeySearch)).ToList();
            var books = allBooks.Skip(page * 3).Take(pageSize).ToList();
            var totalPage = (int)Math.Ceiling((decimal)allBooks.Count / pageSize);

            return PartialView("~/Views/Shared/_ShowBookFollowKeySearch.cshtml", new PaggingModel
            {
                Books = books,
                TotalPage = totalPage
            });
        }

        [HttpGet]
        public ActionResult ShowBookFollowPrice(int page = 0, int priceFrom = 0, int priceTo = 0, int sortID = 0)
        {
            var allBooks = db.Books.Where(x => (x.Price >= priceFrom && x.Price <= priceTo)).ToList();
            var books = allBooks.Skip(page * 3).Take(pageSize).ToList();
            var totalPage = (int)Math.Ceiling((decimal)allBooks.Count / pageSize);

            return PartialView("~/Views/Shared/_ShowBookFollowPrice.cshtml", new PaggingModel
            {
                Books = books,
                TotalPage = totalPage
            });
        }

        [HttpGet]
        public ActionResult ShowPriceBook()
        {
            var allPrice = db.FilterPrices.ToList();
            var totalPrice = allPrice.Count();
            return PartialView("~/Views/Shared/_ShowPriceBook.cshtml", new PaggingModel
            {
                Price = allPrice,
                TotalPrice = totalPrice
            });
        }

        public int GetCountBookFollowPrice(double PriceFrom, double PriceTo)
        {
            return db.Books.Where(x => (x.Price >= PriceFrom && x.Price <= PriceTo)).Count(); ;
        }

        [HttpPost]
        public ActionResult GetInforFilterPrice(int FilterID)
        {
            FilterPrice Infor = db.FilterPrices.Where(x => x.FilterID == FilterID).FirstOrDefault();
            var rslt = new
            {
                priceFrom = Infor.PriceFrom,
                priceTo = Infor.PriceTo
            };
            return Json(rslt, JsonRequestBehavior.AllowGet);
        }
    }
}

BS_Project-15112018-20190513T013456Z-001 - Copy/BS_Project-15112018/BS_Project/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BS_Project-15112018-20190513T013456Z-001 - Copy/BS_Project-15112018/BS_Project/Views/Home/BookDetail.cshtml
@using BS_Project.EF
@using BS_Project.DAO;
@model Book
@{
    ViewBag.Title = "BookDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="@Url.Content("~/Content/bookdetail.css")" rel="stylesheet" type="text/css" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.14.1/moment.min.js"></script>

<script src="~/Scripts/BookDetail.js"></script>
<div class="container">
    <div class="col-md-4 single-right-left ">
        <div class="grid images_3_of_2">
            <div class="flexslider">
                <div class="slides" style="text-decoration:none">
                    @*<li data-thumb="" >*@
                    <div style="width: 250px; height:360px" class="thumb-image"> <img src="@Model.ImageBool.Images.FirstOrDefault().ImageURL" data-imagezoom="true" class="img-responsive"> </div>
                    @*</li>*@
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="col-md-8 single-right-left simpleCart_shelfItem">
        <h3>@Model.Name</h3>
        <p><span class="item_price">@Html.Action("FormatMoney", new { money = @Model.Price })  Đ</span></p>
        <div class="rating1">
            <span class="starRating">
                <input id="rating5" type="radio" name="rating" value="5">
                <label for="rating5">5</label>
                <input id="rating4" type="radio" name="rating" value="4">
                <label for="rating4">4</label>
                <input id="rating3" type="radio" name="rating" value="3" checked="">
                <label for="rating3">3</label>
                <input id="rating2" type="radio" name="rating" value="2">
                <label for="rating2">2</label>
                <input id="rating1" type="radio" name="rating" value="1">
                <label for="rating1">1</label>
            </span>
        </div>
        <div class="color-quality">
            <div class="color-quality-right">
                @*<h5><b5>Tác giả:</b5>@Model.Authors.FirstOrDefault().Name</h5>*@
                <h5><b5>Tác giả:</b5>@Html.TextBoxFor(x => x.Authors.FirstOrDefault().Name)</h5>
                <h5><b5>Thể loại:</b5>@Model.Categories.FirstOrDefault().Name</h5>
                <h5><b5>Nhà xuất bản:</b5>@Model.Publisher.Name</h5>
                <h5><b5>Ngày phát hành:</b5>@Model.PublicationDate.Value.ToShortDateString()</h5>
                <h5><b5>View:</b5>@Model.ViewCount</h5>
            </div>
        </div>
        <div class="occasion-cart">
            <div id="@Model.BookID" class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out button2" name="addToCart">
                Thêm vào giỏ hàng
            </div>

        </div>

        <ul class="social-nav model-3d-0 footer-social w3_agile_social single_page_w3ls">
            <li class="share">Share On : </li>
            <li>
                <a href="#" class="facebook">
                    <div class="front"><i class="fa fa-facebook" aria-hidden="true"></i></div>
                    <div class="back"><i class="fa fa-facebook" aria-hidden="true"></i></div>
                </a>
            </li>
            <li>
                <a href="#" class="twitter">
                    <div class="front"><i class="fa fa-twitter" aria-hidden="true"></i></div>
                    <div class="back"><i class="fa fa-twitter" aria-hidden="true"></i></div>
                </a>
            </li>
            <li>
                <a href="#" class="instagram">
                    <div class="front"><i class="fa fa-instagram" aria-hidden="true"></i></div>
                    <div class="back"><i class="fa fa-instagram" aria-hidden="true"></i></div>
                </a>
            </li>
            <li>
                <a href="#" class="pinterest">
                    <div class="front"><i class="fa fa-linkedin" aria-hidden="true"></i></div>
                    <div class="back"><i class="fa fa-linkedin" aria-hidden="true"></i></div>
                </a>
            </li>
        </ul>
    </div>
    <!-- /new_arrivals -->
    <div class="responsive_tabs_agileits">
        <div id="horizontalTab">
            <ul class="resp-tabs-list">
                <li>Thông tin về sách</li>
                <li>Tác giả</li>
            </ul>
            <div class="resp-tabs-container">
                <!--/tab_one-->
                <div class="tab1">
                    <div class="single_page_agile_its_w3ls">
                        <p>@Model.Overview</p>
                        <p>@Model.Details</p>
                    </div>
                </div>
                <!--//tab_one-->
                <div class="tab2">
                    @Html.Action("returnAuthor", "Author", new { bookID = Model.BookID })
                </div>
            </div>
        </div>
    </div>
    <!-- //new_arrivals -->
    <div class="row">
        <div class="col-xs-12">
            <div id="comment" class="comment-box">
                <div class="comment-title" style="margin-top: 30px;">
                    <b>Bình luận về sản phẩm</b>
                </div>
                <div class="resp-tabs-container">
                    <div class="tab1">
                        <div class="single_page_agile_its_w3ls">
                            @*<div style="width: 200px; height: 100px;">sdfdsf</div>*@
                            @{
                                string numberBoardAnnouncement = string.Empty;
                                List<Comment> cmt = CommentsDAO.GetComments(Model.BookID);
                                foreach (Comment d in cmt)
                                {
                                    string detailComments = "detailComments" + d.CommentID;
                                    numberBoardAnnouncement += string.Format("{0}{1}", (numberBoardAnnouncement != string.Empty) ? "," : "", d.CommentID);
                                    <div id="@detailComments" class="sortable-item-detail">
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><br />
    @{
        int BookID = Model.BookID;
        var userName = Session["userHello"];
        var userID = Session["UserID"];
    }
    <p class="form" id="comment-form" style="visibility: hidden">
        <input type="text" name="content" id="comment_content" class="form-control" placeholder="Hãy đóng góp ý kiến của bạn ở đây." />
        <button type="button" id="btnRegisterComments" class="btn btn-primary btn-add-comment" onclick="RegisterComments();">Thêm bình luận</button>
        <input type="hidden" id="BookID" value="@BookID" />
        <input type="hidden" id="userName" value="@userName" />
        <input type="hidden" id="userID" value="@userID" />
        <input type="hidden" id="hdnNumberBoardAnnouncement" value="@numberBoardAnnouncement" />
    </p>
</div>

BS_Project-15112018-20190513T013456Z-001 - Copy/BS_Project-15112018/BS_Project/Views/Home/Categories.cshtml
@using BS_Project.Models;
@model IEnumerable<BS_Project.EF.Category>


@foreach (var item in Model)
{
    <li><a href="@Url.Action("ShowBook","Book", new { condition = 1, idcategory = item.CategoryID})">@item.Name</a></li>
}

BS_Project-15112018-20190513T013456Z-001 - Copy/BS_Project-15112018/BS_Project/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BS_Project-15112018-20190513T013456Z-001 - Copy/BS_Project-15112018/BS_Project/Views/Home/HeaderCart.cshtml
@model List<BS_Project.Models.CartItem>


@if (ViewBag.Status != null)
{

    <div class="wthreecartaits wthreecartaits2 cart cart box_1">
        @*<a href="/OrderBook/Index"><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></a>*@
        <form action="/gio-hang" method="post" class="last">
            <button class="w3view-cart" type="submit" name="submit" value=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></button>
            @if (Model.Count == 0)
            {
                @*<span id="totalBook" class="cm-number">@ViewBag.BookBorrowed</span>*@
            }
            else
            {
                @Model.Count
                @*<span id="totalBook" class="cm-number">@Session["OrderCart"]</span>*@
            }
        </form>

    </div>
}
else
{
    <div class="wthreecartaits wthreecartaits2 cart cart box_1">
        @*<a href="/OrderBook/Index"><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></a>*@

        <form action="" class="last" id="btnOrderCart">
            <button class="w3view-cart" type="submit" name="submit" value=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></button>
        </form>
        @*<div class="last">
                <a href="#" class="w3view-cart" data-toggle="modal" data-target="#myModal"><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></a>
            </div>*@

    </div>
}

BS_Project-15112018-20190513T013456Z-001 - Copy/BS_Project-15112018/BS_Project/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using BS_Project.EF;
@model IEnumerable<Book>
<style>
    .img-responsive {
        height: 255px;
        width: 249px;
    }

    .pro-image-back {
        height: 255px;
        width: 249px;
    }
    /*div.col-md-3.product-men{
        height:450px;
    }*/
    .book-name {
        height: 30px;
    }
</style>
<!-- /new_arrivals -->
<div class="container">
    <h3 class="wthree_text_info">DANH SÁCH <span>SẢN PHẨM</span></h3>
    <div id="horizontalTab">
        <ul class="resp-tabs-list">
            <li> BÁN CHẠY</li>
            <li> MỚI</li>
            <li><a style="color:#000000" href="@Url.Action("showBook","Book", new { condition = 3 })"> Tất cả </a></li>
        </ul>
        <div class="resp-tabs-container">
            <!--/tab_one-->
            <div class="tab1">
                @foreach (var item in (List<Book>)ViewData["listHot"])
                {
                    <div class="col-md-3 product-men">
                        <div class="men-pro-item simpleCart_shelfItem">
                            <div class="men-thumb-item">
                                <img class="img-responsive" src="@item.ImageBool.Images.FirstOrDefault().ImageURL" />
                                <img src="@item.ImageBool.Images.FirstOrDefault().ImageURL" alt="" class="pro-image-back">
                                <div class="men-cart-pro">
                                    <div class="inner-men-cart-pro">
                                        <div style="background-color:#2fdab8;color:white;z-index:5">
                                            <a href="@Url.Action("BookDetail", "Home", new { id = item.BookID })">
                                                @item.Overview
                                            </a>
                                        </div>
                                        <a href="@Url.Action("BookDetail", "Home", new { id = item.BookID })" class="link-product-add-cart">Xem Chi Tiết</a>
                                    </div>
                                </div>

                            </div>
                            <div class="item-info-product ">
                                <h4 class="book-name"><a href="@Url.Action("BookDetail", "Home", new { id = item.BookID })" title="@item.Name">@item.Name</a></h4>
                                <div class="info-product-price">
                                    <span class="item_price"><span class="">@Html.Action("FormatMoney", new { money = @item.Price })  Đ</span></span>
                                </div>
                                <div id="@item.BookID" class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out button2" name="addToCart" style="cursor:pointer">
                                    Thêm vào giỏ hàng
                                </div>
                                @*<div class="link-product-add-cart snipcart-details single-item" name="addToCart" style="cursor:pointer">
                                    <a href="/them-gio-hang?bookID=@item.BookID&Quantity=1">Add To Cart</a>
                                </div>*@
                            </div>
                            @*<span class="product-new-top">View: @item.ViewCount</span>*@
                        </div>
                    </div>
                }
                <div class="clearfix"></div>
            </div>
            <!--/tab_two-->
            <div class="tab2">
                @foreach (var item in (List<Book>)ViewData["listNew"])
                {
                    <div class="col-md-3 product-men">
                        <div class="men-pro-item simpleCart_shelfItem">
                            <div class="men-thumb-item">
                                <img class="img-responsive" src="@item.ImageBool.Images.FirstOrDefault().ImageURL" />
                                <img src="@item.ImageBool.Images.FirstOrDefault().ImageURL" alt="" class="pro-image-back">
                                <div class="men-cart-pro">
                                    <div class="inner-men-cart-pro">
                                        <div style="background-color:#2fdab8;color:white;z-index:5">
                                            <a href="@Url.Action("BookDetail", "Home", new { id = item.BookID })">
                                                @item.Overview
                                            </a>
                                        </div>
                                        <a href="@Url.Action("BookDetail", "Home", new { id = item.BookID })" class="link-product-add-cart">Quick View</a>
                                    </div>
                                </div>
                                <span class="product-new-top">Mới</span>
                            </div>
                            <div class="item-info-product ">
                                <h4 class="book-name"><a href="@Url.Action("BookDetail", "Home", new { id = item.BookID })" title="@item.Name">@item.Name</a></h4>
                                <div class="info-product-price">
                                    <span class="item_price"><span class="">@Html.Action("FormatMoney", new { money = @item.Price })  Đ</span></span>
                                </div>
                                <div id="@item.BookID" class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out button2" name="addToCart" style="cursor:pointer">
                                    Add to cart
                                </div>
                                @*<div class="link-product-add-cart snipcart-details single-item" name="addToCart" style="cursor:pointer">
                                    <a href="/them-gio-hang?bookID=@item.BookID&Quantity=1">Add To Cart</a>
                                </div>*@
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

BS_Project-15112018-20190513T013456Z-001 - Copy/BS_Project-15112018/BS_Project/Views/Home/Login.cshtml
@if (Session["userName"] != null)
{
    if ((bool)Session["blockID"])
    {
        <script>
            alert("Đăng nhập thành công");
        </script>
        //2 là người mua sách, được quyền vào Trang Web
        if ((int)Session["roleID"] == 2)
        {
            <meta http-equiv="refresh" content="1;https://localhost:44324/">
        }
        //1 là Admin - chạy thẳng vào trang Admin
        if ((int)Session["roleID"] == 1)
        {
            <meta http-equiv="refresh" content="1;https://localhost:44324/Store/Home/Index">
        }
    }
    else
    {
        <script>
            alert("Tài khoản của bạn đã bị block! Vui lòng đăng nhập lại sau.");
        </script>
        Session["userName"] = null;
        <meta http-equiv="refresh" content="1;Index">
    }
}
else
{
    <script>

        alert("Sai tên đăng nhập hoặc mật khẩu!!!");
    </script>

    Session["userName"] = null;
    <meta http-equiv="refresh" content="1;Index">
}

BS_Project-15112018-20190513T013456Z-001 - Copy/BS_Project-15112018/BS_Project/Views/Home/Publisher.cshtml
@using BS_Project.Models;
@model IEnumerable<BS_Project.EF.Publisher>


@foreach (var item in Model)
{
    <li><a href="@Url.Action("ShowBook","Book", new { condition = 2, idpublisher = item.PublisherID})">@item.Name</a></li>
}

BS_Project-15112018-20190513T013456Z-001 - Copy/BS_Project-15112018/BS_Project/Views/Home/Register.cshtml
@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>